# Global LLM configuration
[llm]
api_type = 'ollama'
model = "qwen2.5-coder:latest"
base_url = "http://host.docker.internal:11434/v1"
api_key = "ollama"
max_tokens = 4096
temperature = 0.0

# Optional configuration for specific LLM models
[llm.vision]
api_type = 'ollama'
model = "qwen2.5-coder:latest"
base_url = "http://host.docker.internal:11434/v1"
api_key = "ollama"
max_tokens = 4096
temperature = 0.0